### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by cyco130** [rakkasjs/rakkasjs#1]
Next.js has an [image optimization feature](https://nextjs.org/docs/basic-features/image-optimization) that Rakkas lacks. [Imagetools](https://github.com/JonasKruckenberg/imagetools) seems to offer similar features as a Vite plugin. We should investigate and either provide an integration example or add new features for deeper integration (an `Image` component?) if we deem necessary.

**Comment by JcdeA** [comment]
This project seems cool, I'll investigate more if I have time.

The Next.js Image component does help prevent layout shifting and such, but it's very complicated to actually style the wrapping span component (which is responsible for preventing layout shifting), as the component's className and style props apply to the inner img component.

The result is that applying things like shadows is possible, but is unnecessary harder to implement.

We should also try to have a way to generate blurred images dynamically. Next.js does support this, but only with statically imported images (ex `import checkSvg from 'public/images/check.png`).

**Comment by cyco130** [comment]
> This project seems cool, I'll investigate more if I have time.

Thank you for your interest and your suggestions.

>  className and style props apply to the inner img component.

Important pitfall to remember to avoid

> We should also try to have a way to generate blurred images dynamically.

I know little about image processing but [sharp](https://sharp.pixelplumbing.com/), the image manipulation library that [Imagetools](https://github.com/JonasKruckenberg/imagetools) uses seems to support it, so it sho
uld be doable.

> Next.js does support this, but only with statically imported images (ex `import checkSvg from 'public/images/check.png`).

This gives the bundler used by the framework (webpack for Next.js, vite for Rakkas) a chance to preprocess the image. I'm not sure how else it could be implemented. Trying to process all static assets would be expensive.

**Comment by JcdeA** [comment]
> This gives the bundler used by the framework (webpack for Next.js, vite for Rakkas) a chance to preprocess the image. I'm not sure how else it could be implemented. Trying to process all static assets would be expensive. 

I was thinking about dynamically generating the blurred images and caching them, which is what next does for image optimization iirc.
 
An "images" field in a config file or such with allowed domains should usually be good enough regarding security. If we wanted to we could add farther restrictions.

I've never used sharp (or any image processing library on node, to be frank) before, so I'll need to investigate more.

**Comment by nitedani** [comment]
Here is my experiment, I'm using sharp so it works only with nodejs: https://github.com/nitedani/rakkas-img-experiment

**Comment by cyco130** [comment]
This solves pretty much everything: https://unpic.pics/img/

**Comment by cyco130** [comment]
I think both [Imagetools](https://github.com/JonasKruckenberg/imagetools) and [Unpic](https://unpic.pics/img/) are more than adequate solutions for this. Closing.
