### ISSUE TITLE
Rakkas should not error if hash element not found during scroll resolution

### ISSUE THREAD

**Issue by lawrencecchen** [rakkasjs/rakkasjs#114]
I'm using Clerk, and their auth component stores state in the URL hash. Rakkas' scroll restoration logic causes this error:

<img width="1463" alt="Screenshot 2023-04-07 at 1 52 54 AM" src="https://user-images.githubusercontent.com/54008264/230577940-36d6f5a7-d379-4811-8621-d54817bd84ea.png">
 
Reproduction with a fresh Rakkas project (0.7.0-next.10):

<img width="1728" alt="Screenshot 2023-04-07 at 2 01 42 AM" src="https://user-images.githubusercontent.com/54008264/230578969-85f098fd-91e9-4e16-b814-adf272e8991e.png">

**Comment by cyco130** [comment]
Should be fixed `0.7.0-next.11`.
