### ISSUE TITLE
Support lazy queries or add a "skip" parameter to useServerSideQuery() options

### ISSUE THREAD

**Issue by rondonjon** [rakkasjs/rakkasjs#115]
It seems that there is currently no way in RakkasJs to delay the submission of a server-side query while the parameters are still unknown or being provided by the user.

While this may seem like an unusual request, it is actually a pretty common use-case due the React requirement that the number and the order of hooks must never change while a component is mounted.

Suppose (intentionally simplified) we have a search form that takes a query string and displays the results:

```
const Form = () => {
  const [queryString, setQueryString] = useState("")
  const { data: results } = useServerSideQuery(async () => {
    return db.findResults(queryString)
  })
  ...
```

How can we now prevent queries, for instance, while the user is still typing or the search term is too short?

With the current implementation, we would probably need to move the query to a different component and mount that component conditionally, and thus either run or skip the hook.

The Apollo project has added a `skip: boolean` parameter to the query options to solve this a bit more conveniently. By passing `true`, we can keep the hook in place but request that the actual request should not (yet) be made.

Alternatively, Apollo has "lazy queries" that don't return the query result as the hook result, but a function that we can call once we're ready. The outcome is similar, with a slightly different coding convention.

Since the latter are (technically) working pretty much like mutations, I guess the "solution" for RakkasJs is a bit of syntactical sugar on top of `useServerSideMutation()`, exported under a `use...Query()` name? 🤔

**Comment by nitedani** [comment]
Support for this was added: https://github.com/rakkasjs/rakkasjs/pull/105
0.7.0-next.10 has some issues
Should work well in the next release

Example:
```tsx
const { data: results } = useServerSideQuery(
  async () => {
    return db.findResults(queryString);
  },
  { enabled: queryString.length > 3 }
);
```
