### ISSUE TITLE
Wrap functions in hooks in useCallback()

### ISSUE THREAD

**Issue by rondonjon** [rakkasjs/rakkasjs#116]
It seems that some of the core hooks in RakkasJs that return functions don't wrap these functions in `useCallback()` and hence [recreate these functions on every render pass](https://stackoverflow.com/questions/71265042/what-is-usecallback-in-react-and-when-to-use-it), potentially resulting in unnecessary registrations and deregistrations of event handlers.

Example:

https://github.com/rakkasjs/rakkasjs/blob/main/packages/rakkasjs/src/features/use-mutation/lib.ts

```
export function useMutation<T, V = void>(
	mutationFn: MutationFunction<T, V>,
	options: UseMutationOptions<T, V> = {},
): UseMutationResult<T, V> {
	...

	async function doMutate(vars: V) {                  <--- here
		...
	}

	function mutate(vars: V) {                  <--- here
		reset.current = false;
		return doMutate(vars);
	}
	
	return {
		status,
		data,
		error,
		isError: status === "error",
		isIdle: status === "idle",
		isLoading: status === "loading",
		isSuccess: status === "success",
		reset() {                                           <--- here
			setStatus("idle");
			setData(undefined);
			setError(undefined);
			reset.current = true;
		},
		mutateAsync: mutate,
		mutate(vars: V) {                                               <--- here
			mutate(vars).catch(() => {
				// Do nothing
			});
		},
	} as any;
}
```

**Comment by cyco130** [comment]
Thank you for reporting. I was aware of the issue but couldn't find the time to fix it. It'll be fixed on the next release.
