### ISSUE TITLE
Throw if server-side function cannot be transformed

### ISSUE THREAD

**Issue by rondonjon** [rakkasjs/rakkasjs#117]
This is just a suspicion, and maybe I'm completely wrong, but could it be that the server-side transformation is not aborted if the passed function cannot be extracted because it was passed in a variable instead of inline?

I would like to use a slightly different call / return signature for my server-side functions and have hence written a wrapper hook that accepts a server-side function and generates a new function from it which is then passed to `useServerSideMutation()`.

```
export const useCustomMutation = <P, R>(f: MutationFunction<P, R>, ...) => {
  ...
  const internalOptions = {...}
  ...
  const { isLoading, mutateAsync, data: internalData, isError } = useServerSideMutation(f, internalOptions)
  ...
  const data = {...}
  ...
  return { ... }
}
```

Now I am getting a client-side runtime error:

```
Uncaught (in promise) Error: Cannot serialize value because it is a function (https://github.com/brillout/json-serializer)
```

I'm not all the way down the rabbit hole, but I suppose it is related to `isRunServerSideCall()` in `/run-server-side/implementation/transform/transform-client-side.ts`, and that the transformation only works if the function is passed to `useServerSideMutation()` as an inline parameter and not as (mutable / variable) `f`, is that right?

How can I work around this?

Suggestion: if Babel cannot transform a server-side function, it should throw and raise an error.

**Comment by cyco130** [comment]
After giving this some thought, unfortunately this is not something that can be analyzed for the general case ahead of time. It would work if `f` was a module scope function. All I can hope for is to improve the docs and maybe make the error message more explicit, at least in dev. Improving error messages all over the board is necessary anyway.
