### ISSUE TITLE
Multiple Actions Per Page

### ISSUE THREAD

**Issue by alrightsure** [rakkasjs/rakkasjs#122]
Is there anyway to have multiple actions per page? I understand that the ``useServersideMutation`` function could accomplish this, but wiring a form into that is not that elegant or graceful. I looked over the docs and I didn't seem to see any way to accomplish this, but I also didn't see anything specifically stating this wasn't possible.

I would like to continue to use forms but have multiple actions on one page (I.E. an admin dashboard with CRUD operations). This is a major drawback of Remix and was hoping to see some solution on Rakkas.

Thanks!

**Comment by cyco130** [comment]
There is an undocumented `useFormMutation` function that decouples form actions from pages. There are a few remaining rough edges but I'm hoping that they will replace route-based actions in the feature. Here's a (crude) usage example: https://stackblitz.com/edit/github-5kdqbg?file=src%2Froutes%2Findex.page.jsx

Apart from that, you can use [API routes](https://rakkasjs.org/guide/api-routes) to define POST handlers or you can use hidden inputs to differentiate between actions on the same route.

**Comment by alrightsure** [comment]
That looks awesome! I really appreciate you making an example too. Thanks!
