### ISSUE TITLE
Mantine emotion support dropped

### ISSUE THREAD

**Issue by tigawanna** [rakkasjs/rakkasjs#156]
Hey there, Thanks for your great framework.
I tried to use the  Mantine example and it seems like the new version removed emotion support

> Mantine no longer depends on [Emotion](https://emotion.sh/) for styles generation. All @mantine/* packages are now shipped with native CSS files which can be imported from @mantine/{package}/styles.css

Is the serverside step still necessary? 
Looks like all we need to do now is
```ts
import '@mantine/core/styles.css';
```
Is there a way to do it in here ?
```tsx
import { MantineProvider } from "@mantine/core";
import { startClient } from "rakkasjs";

startClient({
	hooks: {
		wrapApp(app) {
			return (
				<MantineProvider>
					{app}
				</MantineProvider>
			);
		},
	},
});

```

**Comment by cyco130** [comment]
Hi,

The correct place to add global CSS would be the outermost layout (.e.g. `src/layout.tsx`).

But I noticed a more important problem: Mantine 7 is not packaged correctly, it exports ESM modules with `.js` extension but its `package.json` that doesn't have `"type": "module"` which is wrong.

I built a quick example but I had to resort to `pnpm patch` to patch the `package.json` files and add `"type": "module"`. Here's the [repo](https://github.com/cyco130/rakkas-mantine) and here's the [live example](https://stackblitz.com/github/cyco130/rakkas-mantine?file=package.json).

Apart from the patch, what I did was:

- Install `@mantine/core` and `@mantine/hooks` as prod deps (and patch them).
- Install `postcss-preset-mantine` and `postcss-simple-vars` as dev deps.
- Create `postcss.config.cjs` (not `.js`!) and fill it according to Mantine's [getting started docs](https://mantine.dev/getting-started/).
- Create `src/entry-hattip.tsx` to stringify and inject `ColorSchemeScript`.
- Create `src/common-hooks.tsx` to inject the provider (not `entry-client`, provider is needed in both the server and the client).
- Add a root layout to import the CSS file.

If you need other `@mantine` packages, you'll probably need to patch them as well. All package managers have patching capabilities but I only use `pnpm` so I can only guide you for that:

- Run `pnpm patch @mantine/whatever`
- `pnpm` will create a temp directory and prompt you to edit it. Open that dir, and add `"type": "module"` to `package.json`.
- Follow the prompt and run `pnpm patch-commit <temp-dir-name>`.

And you're done.

I'll file an issue to the Mantine repo when I have more time, only _they_ can fix it properly.

I'll keep the issue open until I update the example in the repo. But I want to wait for them to fix the ESM/CJS bug first.

**Comment by tigawanna** [comment]
thanks for the response

**Comment by cyco130** [comment]
Mantine version `7.0.1-alpha.0` doesn't require patching anymore. I'll update the example in the repo when it's released on `@latest`.

**Comment by cyco130** [comment]
Mantine 7.0.1 is released and it doesn't need the patch. I updated the [example in the repo](https://stackblitz.com/github/rakkasjs/rakkasjs/tree/main/examples/mantine?file=src%2Fentry-hattip.tsx).

It's also now (version `0.7.0.next-20`, just released) possible to return a `ReactElement` from "emitToDocumentHead` to avoid the silly `renderToStaticMarkup` dance in the example above (it was an obvious oversight on my part when designing that API 😅).

I also use Mantine quite frequently. To me it's very much welcome news that they ditched Emotion (which didn't play well with streaming SSR). Yay :)
