### ISSUE TITLE
[Docs] Navigation menu scroll position is not persisted upon navigation

### ISSUE THREAD

**Issue by Filipeue** [rakkasjs/rakkasjs#165]
## Actual behaviour:

Every time I navigate to some page in sidebar menu the menu is scrolled to the top.

![image](https://github.com/rakkasjs/rakkasjs/assets/30953532/29341be3-e777-40e7-8274-6007da199e93)

## Expected behaviour

The menu scroll position is persisted upon navigation.

**Comment by cyco130** [comment]
Ah yes, I've been too lazy to fix it for years :)

**Comment by cyco130** [comment]
Finally fixed!
