### ISSUE TITLE
make scrolling to top on form submit optional

### ISSUE THREAD

**Issue by alexander-entin** [rakkasjs/rakkasjs#166]
something like `useSubmit({ scroll: false })`

currently I do:
````TypeScript
	const { submitHandler } = useSubmit({
		onSettled() {
			const scrollTo = window.scrollTo
			window.scrollTo = x => x
			setTimeout(() => {
				window.scrollTo = scrollTo
			}, 100)
		}
	})
````
is there a better way?

thank you!

**Comment by cyco130** [comment]
Implemented in 0.7.0-next.25 (currently being published). `useSubmit` now accepts `scroll` and `replace` options just like `navigate` to control the scrolling and history push/replace behavior.

In short, `{ scroll: false }` now works as suggested in the OP.
