### ISSUE TITLE
Issues in version 0.7.0-next.44

### ISSUE THREAD

**Issue by tigawanna** [rakkasjs/rakkasjs#247]
I've ran into 2  issues

- Head tags overwrite any data-attributes set to the html

Am using data attributes to set the site's theme server side 
 ```js
       emitToDocumentHead() {
        const cookie_theme = "light";
        return `
    <link rel="icon" type="image/svg+xml" href="/site.svg" />
    <script>
      (function() {
        document.documentElement.setAttribute("data-theme","${cookie_theme}");
      })();
     </script>
   
  `;
      },
 ```
 I've noticed using the `<Head/>`  component in the pages will remove the `data-theme` atrribute from the html

https://github.com/rakkasjs/rakkasjs/assets/72096712/1d52d9d3-1ddb-4949-ad93-0908eeb1cea4

-  `useLocation` will cause a crash duing a HMR refresh
![Screenshot 2024-03-15 062202](https://github.com/rakkasjs/rakkasjs/assets/72096712/ed08fc43-946b-4682-b4f9-ea8471759110)

```tsx
import { Head, Page, useLocation } from "rakkasjs";

const HomePage: Page = function HomePage() {
  const {current} = useLocation()
  return (
    <main>
      <Head title="Home" description="Rakkas demo homepage "/>
      <h1>Hello world!</h1>
      <p>Welcome to the Rakkas demo page 💃</p>
      
      <h2>Currently in {current.toString()} </h2>

      <p>
        Try editing the files in <code>src/routes</code> to get started or go to
        the{" "}
        <a href="https://rakkasjs.org" target="_blank" rel="noreferrer">
          website
        </a>
        .
      </p>
      <p>
        You may also check the little <a href="/todo">todo application</a> to
        learn about API endpoints and data fetching.
      </p>
    </main>
  );
};

export default HomePage;


````

 [minimal reproduction](https://github.com/tigawanna/minimal-reproduction-rakkas)

**Comment by CanRau** [comment]
maybe #240 or #242 fixes some of those?

also note that `emitToDocumentHead` has been deprecated in #211 
```
@deprecated
Use emitToSyncHeadScript, emitServerOnlyHeadElements or the normal Head component instead.
```

**Comment by tigawanna** [comment]
oh , had no idea about emitToDocumentHead

**Comment by cyco130** [comment]
Hi!

Thanks for the detailed report!

The head clash is caused by Rakkas now wanting to "own" the html/head/body attributes. I sent a PR that shows how I would solve the dark mode problem in the new version of Rakkas. There are a few higher level hooks now so hopefully we won't need `emitToDocumentHead` anymore.

I just published a 0.7.0-next.45 that includes a fix for he HMR crash (among other things).

**Comment by cyco130** [comment]
Actually dark mode (and other type of client hints) is probably the best idea for the next Rakkas plugin. I know @CanRau is working on something, maybe he'll share it when it's done :)

**Comment by tigawanna** [comment]
the solution in the PR is pretty neat too my objective was avoiding hydration errors and flickers

**Comment by CanRau** [comment]
Hey, I hope I can continue work on it soon, maybe tomorrow or day after 🤞🏼
