### ISSUE TITLE
scrollGroupId undefined error

### ISSUE THREAD

**Issue by tigawanna** [rakkasjs/rakkasjs#253]
![image](https://github.com/rakkasjs/rakkasjs/assets/72096712/63226288-6bed-4127-87f0-54595371129d)

encounterng this error when i call `navigate`  ,it's alittle random and a full page refresh fixes it temporarily , callig navigate multile times will cause it again

**Comment by cyco130** [comment]
I believe it was fixed [here](#252). `0.7.0-next.47` is being published right now. (Feel free to reopen if it doesn't fix it).
