### ISSUE TITLE
Question: is the cli necessary? Or is it enough to use the vite plugin directly?

### ISSUE THREAD

**Issue by ianldgs** [rakkasjs/rakkasjs#262]
If a project already uses vite, and will be deployed with docker, is the `rakka` / `rakka build` commands required? Or would `vite` / `vite build` be enough? Asking because of using it with the built-in [NX](https://nx.dev/) vite plugin, which will call the `vite` api, not `rakka`. So being able to justs add the plugin would make it compatible with NX without the need to write a custom plugin or use of custom commands for the project.

**Comment by CanRau** [comment]
Took a quick look and it seems to do more than just calling `vite` as it's using vavite under the hood so I guess you need the `rakkas` cli
https://github.com/rakkasjs/rakkasjs/blob/main/packages/rakkasjs/src/cli/build.ts

**Comment by cyco130** [comment]
Currently the CLI is necessary for coordinating the two builds (client and server). It will be less necessary when Vite's new [Environment API](https://deploy-preview-16471--vite-docs-main.netlify.app/guide/api-vite-environment.html) lands. When it does, you swill be able to build with `vite build` but the CLI will stay for other features and backwards compatibility.
