### ISSUE TITLE
Incremental static builds

### ISSUE THREAD

**Issue by cyco130** [rakkasjs/rakkasjs#27]
Gatsby has [this feature](https://www.gatsbyjs.com/blog/2020-04-22-announcing-incremental-builds/): We can think of it as the static counterpart of incremental rendering (#23).

**Comment by brillout** [comment]
Especially for image pre-processing.

**Comment by cyco130** [comment]
0.6 has partial support with `rakkas render` to re-render select paths. Unfortunately full support is not possible because, unlike Gatsby, Rakkas doesn't know the data dependency graph of an app.
