### ISSUE TITLE
Support for React 18 features

### ISSUE THREAD

**Issue by cyco130** [rakkasjs/rakkasjs#3]
React 18 will bring new and exciting features that we should support:
- Suspense for data fetching (including in SSR)
- Server components
- `startTransition`

**Comment by MarkLyck** [comment]
Any update on this?

**Comment by cyco130** [comment]
See [the other issue](https://github.com/rakkasjs/rakkasjs/issues/2#issuecomment-1066082161) for streaming SSR and suspense in SSR. For server components, the Vite community is [still discussing](https://github.com/vitejs/vite/discussions/4591) the best way to approach it.

**Comment by brillout** [comment]
For RSC, also see https://github.com/facebook/react/pull/22952.

**Comment by cyco130** [comment]
This is done in 0.6 except for server components. Server components is tracked on #38
