### ISSUE TITLE
Bug: dev server returns 404 for `/virtual:rakkasjs:start-client.js`

### ISSUE THREAD

**Issue by tkamenoko** [rakkasjs/rakkasjs#32]
Local development server returns 404 for `/virtual:rakkasjs:start-client.js` , and that causes blank stylesheets. Note that runing `rakkas build` works as expected.

Env:
- OS: Windows11 64bit
- Browser: vivaldi 5.1.2567.57 (Stable channel) (64-bit) 
- Node: 16.13.2
- npm: 8.2.1
- rakkas: 0.5.1

**Comment by tkamenoko** [comment]
terminal:
```
Server listening on http://localhost:3000
200 GET      /
404 GET      /virtual:rakkasjs:start-client.js
200 GET      /
404 GET      /virtual:rakkasjs:start-client.js
```

Browser dev tool:
![rakkas-error](https://user-images.githubusercontent.com/41364327/156796991-3ee8ac0b-ccf0-43ac-9075-608d950de2ed.png)

**Comment by cyco130** [comment]
Thankd for reporting @tkamenoko.

I believe I diagnosed and [solved](https://github.com/rakkasjs/ci/actions) this issue. But, unfortunately, I don't have a Windows machine handy. Would you be so kind to try version `0.5.2@canary` and see if it works for you too? If it does, I'll release it as `0.5.2`.

**Comment by tkamenoko** [comment]
```
TypeError: Cannot read properties of undefined (reading 'isSelfAccepting')
    at TransformContext.transform (C:\Users\tkamemnoko\myproject\node_modules\@rakkasjs\cli\node_modules\vite\dist\node\chunks\dep-5496817b.js:81289:43)
```

**Comment by tkamenoko** [comment]
IMO, `vite` tries to load `virtual:rakkasjs:start-client.js` (not starts with a slash), but it fails because of wrong path name.

I injected `console.log` arround the error line like this: 

```js
// myproject\node_modules\@rakkasjs\cli\node_modules\vite\dist\node\chunks\dep-5496817b.js
            // vite-only server context
            const { moduleGraph } = server;
            // since we are already in the transform phase of the importer, it must
            // have been loaded so its entry is guaranteed in the module graph.
            console.log(importer); // INJECTED LOGGING
            const importerModule = moduleGraph.getModuleById(importer);
            const importedUrls = new Set();
```

and the result of terminal output: 

```
500 GET      /
virtual:rakkasjs:start-client.js
C:/Users/tkamemnoko/myproject/node_modules/rakkasjs/dist/client.mjs?v=1ef56503
C:/Users/tkamemnoko/myproject/node_modules/rakkasjs/dist/chunk-BYZC6E5I.mjs?v=1ef56503
C:/Users/tkamemnoko/myproject/node_modules/rakkasjs/dist/chunk-CSRYYC67.mjs?v=1ef56503
C:/Users/tkamemnoko/myproject/node_modules/rakkasjs/dist/chunk-MQX4TKX6.mjs?v=1ef56503
/@virtual:vite-plugin-virtual/virtual:rakkasjs:page-imports
```

**Comment by cyco130** [comment]
`resolveId` resolves all the `virtıal:rakkasjs:*` modules but Vite requires the entry from `index.html` to be absolute (relative to the root, actually). So `resolveId` resolves anything that contains `virtıal:rakkasjs:` to `virtıal:rakkasjs:...`. So `/virtual:rakkasjs:start-client.js` resolves to `virtual:rakkasjs:start-client.js`. That part is normal.

In any case, it seems like a different problem. The log shows that the entry resolves fine. Could you you delete the directory `node_modules/.vite` and try again?

**Comment by tkamenoko** [comment]
@cyco130 Sorry for my late response.

I removed `node_modules/.vite` and started dev server, then I got the same error.  However, after few times of restarting dev server, I got a valid response.

It may be caused by pre bundling. I use [linaria](https://github.com/callstack/linaria) for styling. but I forgot to append 
[vite's `optimizeDeps.include` config](https://vitejs.dev/config/#optimizedeps-include) . After fixing the config, dev server works as expected.

I made a sample project at https://github.com/tkamenoko/rakkas-linaria . Feel free to use this repo for reproducing the issue.

**Comment by cyco130** [comment]
Great to hear! I was trying to remember where I remember that exact message and now I do, it was caused by styled-components when it's not in `optimizeDeps.include`, no wonder linaria does the same. It's a Vite problem which may or may not have been solved in [the current beta](https://github.com/vitejs/vite/pull/6758). I'll release 0.5.2 in a few minutes and experiment with the new beta later.
