### ISSUE TITLE
Accessing MDX frontmatter in layouts

### ISSUE THREAD

**Issue by trevorblades** [rakkasjs/rakkasjs#37]
For the last week, I've been on a quest to spin up a Rakkas site that uses MDX v2, and I finally managed to do so using the `@cyco130/vite-plugin-mdx` plugin—thanks for that! 🙌

Now the last hurdle that I'm facing is accessing frontmatter from my MDX pages. I'm using `remark-frontmatter` and `remark-mdx-frontmatter` to parse the frontmatter and assign it to named exports in my pages. Ideally, I would like for the frontmatter to be accessible by a layout component so I can render SEO tags and page headings like so:

src/pages/page.mdx:

```mdx
---
title: Getting started
---

Post content to follow
```

src/pages/layout.jsx:

```jsx
export default function Layout({children, context}) {
  return (
    <>
      <Helmet title={context.title} />
      <h1>{context.title}</h1>
      {children}
    </>
  )
}
```

I experimented with defining a `load` function in my MDX file:

```mdx
---
title: Getting started
---

export const load = () => ({context: {title}})

Post content to follow
```

However, this only makes `title` available to the page, not its layout. I could just use the MDX default export to explicitly use a custom layout component for the page. And this works, the page title and heading are rendered 🎉 

```mdx
---
title: Getting started
---

export const load = () => ({context: {title}})
export {Layout as default} from '../components/Layout'

Post content to follow
```

To get rid of the `load` function in each file, I could make a remark plugin that automatically exports frontmatter as the `context` property returned from a `load` export, similar to how [remark-mdx-frontmatter](https://www.npmjs.com/package/remark-mdx-frontmatter) and [remark-mdx-frontmatter-alt](https://www.npmjs.com/package/remark-mdx-frontmatter-alt) add exports to the MDX file that's being transformed.

What I'm wondering is if there's a way to pass context _up_ from pages to their layouts, so that I can reduce the amount of boilerplate I have to add to each MDX file that I make. That would remove the need for the default export in each MDX file. Can context even be propagated up in that way in Rakkas?

I know that v0.6 is being worked on, and wonder if that changes anything about the way that context is loaded, or might be able to support this use case better. I hope I described the problem that I'm trying to solve (using frontmatter in layouts) adequately, and if there is anything I can do to help make this a reality, I'm up for it 👍

**Comment by cyco130** [comment]
Hi!

Thanks for bringing this up. The use case definitely  requires a solution, in fact I could use it for Rakkas's docs too. I published a quick solution as `0.5.4`: Now load functions can return a `meta` object in addition to `data` and `context`. They are merged outside in and passed to all components in the stack. See the [test example here](https://github.com/rakkasjs/rakkasjs/tree/main/testbed/general/src/pages/meta).

So now there is a way to pass upward from load functions to components. There is no way to pass data upwards from load functions to load functions or components to components of course: It would be a chicken-egg problem.

> I finally managed to do so using the `@cyco130/vite-plugin-mdx`

It will become the next major version of the official `vite-plugin-mdx` once Vite 3 is released and I will maintain it from then on. It kind of works with Vite 2 but there are some bugs in development mode so your mileage may vary.

> I know that v0.6 is being worked on, and wonder if that changes anything about the way that context is loaded

It changes _everything_ :smile: Unfortunately it's gonna be a very backwards incompatible release. `load` is gone in favor of streaming SSR and Suspense-based `useQuery` and `useServerSideQuery` hooks. [I think you'll find the latter pretty cool!](https://stackblitz.com/edit/use-ssq?file=src%2Froutes%2Findex.page.tsx).

There will be a `preload` function (not implemented yet) for SEO and optimization purposes. But it will be called in parallel for every module on the layout stack so there will be no `context`. Plain React context can now cover all use cases of the old layout context thanks to Suspense. I added the `meta` option to my todo too, the mechanism will be very similar.

I don't have a solution for mdx (pre)load functions preventing HMR yet. After 0.6 is out, we can work on a Remark plugin that exports the frontmatter as meta using the same "tucking it into a function prop" trick as `remark-mdx-frontmatter-alt`. I want Rakkas to support MDX out of the box anyway.

Also feel free to check the 0.6 code base, it's on the `next` branch. I also publish the `rakkasjs@next` package occasionally (it's all you need now, no separate CLI package). It's still pretty rough but I'm aiming to release right after Vite 3, which should be in a month or so.

**Comment by cyco130** [comment]
(PS: Let me know if it solves your problem and I'll close the issue)

**Comment by trevorblades** [comment]
`meta` solves the issue perfectly. Thanks!

I ended up making [a fork of `remark-mdx-frontmatter`](https://github.com/trevorblades/remark-mdx-rakkas) that injects a load function at the top of MDX files. It relies on `remark-frontmatter` to grab the frontmatter YAML or TOML, then parses that into an object, and does:

```js
export const load = () => ({meta: frontmatterObj})
```

Now I can work with MDX pages, and the frontmatter gets sent up to the layout. Perfect 💆‍♂️

```js
// rakkas.config.js
import mdx from '@cyco130/vite-plugin-mdx';
import remarkFrontmatter from 'remark-frontmatter';
import {remarkMdxRakkas} from '@trevorblades/remark-mdx-rakkas';

export default {
  pageExtensions: ['jsx', 'tsx', 'mdx'],
  vite: {
    plugins: [
      mdx({
        remarkPlugins: [remarkFrontmatter, remarkMdxRakkas]
      })
    ]
  }
}
```

Thanks for the extra info and guidance on this issue. I'm really excited to hear about the developments with 0.6, and I love that you're thinking of supporting MDX out of the box. I think that would be a huge differentiating factor for Rakkas. If there's anything I can do to help make that happen, I'd be happy to chip in.

I know that it's still early days, but my roommate and I have been jamming on Rakkas stuff for the last week, and it's been really fun. The page/layout paradigm feels really intuitive, and the framework is generally a pleasure to build with.

**Comment by cyco130** [comment]
That's awesome! I will definitely steal things from your frontmatter fork :)
