### ISSUE TITLE
[FR] Vue Support

### ISSUE THREAD

**Issue by rayfoss** [rakkasjs/rakkasjs#39]
Seems like a missed opportunity to not support the other framework like Redux and Vite did when they realized the functionality they provided was not component framework dependent.

**Comment by cyco130** [comment]
The [next version (0.6)](https://github.com/rakkasjs/rakkasjs/tree/next) delegates much of the low level work to [vavite](https://github.com/cyco130/vavite) and [hattip](https://github.com/hattipjs/hattip) which are independent packages now.

Also the code base is [much better organized](https://github.com/rakkasjs/rakkasjs/tree/next/packages/rakkasjs/src/features) now which will allow me to split other features (API routes, page router, [useServerSideQuery](https://stackblitz.com/edit/use-ssq?file=src%2Froutes%2Findex.page.tsx) etc.) into independent packages later as well.

I'll probably experiment with Preact first but with some help from Vue-savvy folks let's say it's a definite possibility (maybe under a different name, HatTip Pages?)
