### ISSUE TITLE
Missing `types` declaration for exports in rakkasjs@next package.json

### ISSUE THREAD

**Issue by IgnusG** [rakkasjs/rakkasjs#40]
The exports defined [here](https://github.com/rakkasjs/rakkasjs/blob/next/packages/rakkasjs/package.json#L18-L21) are missing the `types` field to point typescript to the right location. Without it typescript complains:

![image](https://user-images.githubusercontent.com/6438760/179846766-94bd3069-b03f-4051-860c-8adbf2d55c5f.png)

Adding `"types": "./dist/index.d.ts"` to the top of this field in rakkas' package.json resolved this issue.

**Comment by cyco130** [comment]
That's weird, for me TypeScript finds the `index.d.ts` in the package root. Even if we add a `types` field it seems you won't be able to find types for `rakkasjs/node-adapter` and `rakkasjs/vite-plugin`. Can I see your `tsconfig.json`? Maybe your `moduleResolution` is set to something different. I'm still hazy about how `Node16` and `NodeNext` resolution modes work. I didn't have much luck with the `exports.types` field so far. 

In any case, I switched to the `typesVersions` field for some other reason. Now published as `0.6.0-next.8`. Please check if it solves the type resolution issue. (I'm still curious about your `tsconfig.json` though, for my other libraries at lease).

**Comment by IgnusG** [comment]
```json
{
	{
	"compilerOptions": {
		"baseUrl": "./",
		"jsx": "react-jsx",
		"target": "ESNext",
		"module": "ESNext",
		"moduleResolution": "NodeNext",
	},
	"include": ["src", "env.d.ts"]
}
```

The culprit here seems to be `moduleResolution`. Switching it back to `Node` makes typescript pickup rakkas' types again.
 
I think typescript's issue here (if `moduleResolution` is set to `NodeNext` - maybe it prioritizes the exports map over the root `index.d.ts` when this is used) is the fact that the root import `"."` is a conditional one and its files `./dist/server.js` and `./dist/client.js` don't share the same name as `./dist/index.d.ts`. If I duplicate `./dist/index.d.ts` and name it `./dist/client.d.ts` and `./dist/server.d.ts` it works again (even without the additional `types` field.

It appears to also not be a problem for either `rakkasjs/node-adapter` nor `rakkasjs/vite-plugin` since their definition files share the same name and typescript picks them up without any hassle.

**Comment by cyco130** [comment]
If it doesn't work, try:

```
"exports": {
	".": {
		"types": "./dist/index.d.js",
		"browser": "./dist/client.js",
		"default": "./dist/server.js"
	},
	...
```

I hope this + `typesVersions` from next.8 works with both `"moduleResolution": "Node"` and `"moduleResolution": "NodeNext"`.

**Comment by cyco130** [comment]
> I hope this + `typesVersions` from next.8 works with both `"moduleResolution": "Node"` and `"moduleResolution": "NodeNext"`.

Yes it does. Skip next.8 and try next.9, it should work now.

**Comment by IgnusG** [comment]
> > I hope this + `typesVersions` from next.8 works with both `"moduleResolution": "Node"` and `"moduleResolution": "NodeNext"`.
> 
> Yes it does. Skip next.8 and try next.9, it should work now.

Thanks @cyco130! Can confirm it works on `.9`
