### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by Innei** [rakkasjs/rakkasjs#47]
Hey, it's me again. I tried to write an SEO library for rakkas and I found that I could migrate next-seo over, so I modified the bundle way of  next-seo library and released a version. But I ran into some problems and got an error in SSR. error [ERR_REQUIRE_ESM]: require() of ES Module, in CSR ta is working.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/innei/git/demo/rakkasjs-demo/node_modules/.pnpm/rakkasjs@0.6.0_yogrrpwgdz2zmfozuavyhqdpum/node_modules/rakkasjs/dist/server.js from /Users/innei/git/demo/rakkasjs-demo/node_modules/.pnpm/rakkas-seo@0.6.0-4_rakkasjs@0.6.0/node_modules/rakkas-seo/lib/meta/defaultSEO.js not supported.
Instead change the require of server.js in /Users/innei/git/demo/rakkasjs-demo/node_modules/.pnpm/rakkas-seo@0.6.0-4_rakkasjs@0.6.0/node_modules/rakkas-seo/lib/meta/defaultSEO.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/innei/git/demo/rakkasjs-demo/node_modules/.pnpm/rakkas-seo@0.6.0-4_rakkasjs@0.6.0/node_modules/rakkas-seo/lib/meta/defaultSEO.js:29:20)
    at Object.<anonymous> (/Users/innei/git/demo/rakkasjs-demo/node_modules/.pnpm/rakkas-seo@0.6.0-4_rakkasjs@0.6.0/node_modules/rakkas-seo/lib/index.js:7:20)
    at async Promise.all (index 0)
    at async nodeImport (file:///Users/innei/git/demo/rakkasjs-demo/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:50619:21)
    at async eval (/src/routes/index.page.tsx:10:31)
    at async instantiateModule (file:///Users/innei/git/demo/rakkasjs-demo/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:50548:9) {
  code: 'ERR_REQUIRE_ESM'
}
```

My repo is here. https://github.com/Innei/rakkas-seo.

The library entry I wrote as: 

```json
// package.json
"main": "lib/index.js", // cjs
  "module": "esm/index.js", // esm
  "unpkg": "lib/index.js",
  "types": "types/index.d.ts",
```

3Q

**Comment by Innei** [comment]
It looks like rakkasjs does not provide cjs export, can you add cjs format export?

```
const rakkasjs_1 = require("rakkasjs"); // error
```

**Comment by Innei** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/41265413/188310012-a4b8496c-e3cb-479b-98d2-0ff7230c8a46.png">

**Comment by cyco130** [comment]
Hi, you may have to name your ESM build output with a `.mjs` extension for SSR to work. Otherwise Node can't run it properly.

**Comment by Innei** [comment]
OK, I have to try.

**Comment by Innei** [comment]
> Hi, you may have to name your ESM build output with a `.mjs` extension for SSR to work. Otherwise Node can't run it properly.

So, I need to provide cjs format entry?

**Comment by cyco130** [comment]
No, what I'm saying is you need your ESM entry to be named .mjs and not .js. Or you can put `type: module` tou your package.json and use .cjs for your CJS and plain .js for your ESM.

**Comment by Innei** [comment]
A new issue. This `virtual:` does not appear in my library esm build output. Maybe in rakkasjs server.js.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/41265413/188311355-2f870622-3597-45af-8231-c1caf239dd04.png">

**Comment by Innei** [comment]
And I've overflowed the cjs build, ESM pure, and set the `type: module` in the package

**Comment by cyco130** [comment]
Oh, got it. You're using Rakkas from your own lib. Then you'll have to add `ssr: noExternal: ["mylib"]` to your `vite.config`. Rakkas is a "special" library that has to be processed by Vite. If you're using it from your own lib, then your lib has to be processed by it too. That's what `noExternal` does.

**Comment by Innei** [comment]
Thanks, solve my issue.
