### ISSUE TITLE
Can't read the properties something of 'usePageContext()'

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#53]
Sometimes using rakkasjs hooks like usePageContext and useLocation throws error showing cant read the properties something of null

**Comment by sharmapukar217** [comment]
also sometimes i get random error showing `TypeError: Invalid URL`

**Comment by sharmapukar217** [comment]
TypeError: Cannot read properties of null (reading 'useLocation')
This was what I got

**Comment by cyco130** [comment]
It's because of this bug: https://github.com/vitejs/vite/issues/3301 It probably kicks in when editing the `entry-client` file. Vite has some problems when doing HMR with React context. I'll see what I can do but it's a long standing issue :/

**Comment by sharmapukar217** [comment]
hey, I think this one was solved by the beta update of `vite-plugin-react`
https://github.com/vitejs/vite/blob/plugin-react@2.2.0-beta.0/packages/plugin-react/CHANGELOG.md

**Comment by cyco130** [comment]
> hey, I think this one was solved by the beta update of `vite-plugin-react` https://github.com/vitejs/vite/blob/plugin-react@2.2.0-beta.0/packages/plugin-react/CHANGELOG.md

Awesome, I'll try it soon. I think Vite 4 is just around the corner anyway. I'll try to coincide Rakkas 0.7 with it.

**Comment by sharmapukar217** [comment]
> > hey, I think this one was solved by the beta update of `vite-plugin-react` https://github.com/vitejs/vite/blob/plugin-react@2.2.0-beta.0/packages/plugin-react/CHANGELOG.md
> 
> Awesome, I'll try it soon. I think Vite 4 is just around the corner anyway. I'll try to coincide Rakkas 0.7 with it.

very excited to see rakkas v0.7 🥳

**Comment by sharmapukar217** [comment]
this is still not fixed

**Comment by cyco130** [comment]
You're right. I'll look into it more thoroughly.

**Comment by cyco130** [comment]
I've been failing to replicate this for sometime. Do you have a repro somewhere? Also, are you on a monorepo setup? I think it might be relevant.

**Comment by sharmapukar217** [comment]
I think it's now fixed. BTW is fast refresh disabled by default on rakkasv7? last time i had to manually enable fast refresh. After enabling fast refresh, i was not getting any context related issues. I'd inform you after using it more. For now closing this issue

**Comment by cyco130** [comment]
> is fast refresh disabled by default on rakkasv7?

Erm, no? That's weird. How did you enable it?

**Comment by sharmapukar217** [comment]
> 

Oh i used react field on rakkas' vite plugin 😃
