### ISSUE TITLE
global styles are not loaded on ssr in development mode

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#58]
I found that the global styles and unocss import is only loaded after the client side hydration and if i disable javascript no style is loaded at all. Although i found a workaround for this by manually adding styles in head using emitToDocumentHead on entry-hattip.ts, but drawback of this is I loose hmr on global css. Are there any other ways?

**Comment by cyco130** [comment]
Should be fixed in version `0.6.2`.

**Comment by sharmapukar217** [comment]
> Should be fixed in version `0.6.2`.

Do you mean `0.6.3`?

**Comment by cyco130** [comment]
I mean `0.6.4`. There has been a series of bad releases :)
