### ISSUE TITLE
serverless deployments not working

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#60]
I tried to deploy my app to vercel and netlify as well but i get internal server error page. I'm using prisma (maybe this is the issue) but I followed the vite config from the rakkasjs-realworld repo. But it is not still working. But On removing prisma it works. I want to know how can I use prisma

**Comment by cyco130** [comment]
Which database engine are you using and where is your database deployed?

**Comment by cyco130** [comment]
Can you access the (deployed) database when running locally?

**Comment by sharmapukar217** [comment]
> Which database engine are you using and where is your database deployed?

i'm using mongodb and i tried using both data proxy way and non data proxy ways

**Comment by sharmapukar217** [comment]
one strange thing. when i run yarn start ( locally i mean ) nothing breaks, not even prisma cjs/esm issue

**Comment by cyco130** [comment]
> one strange thing. when i run yarn start ( locally i mean ) nothing breaks, not even prisma cjs/esm issue

I do use Prisma locally all the time, I don't expect any breakages (including those related to CJS/ESM). But I've never used MogoDB, maybe there's an incompatibility with the MongoDB driver. But then I'd expect the Data Proxy to take care of that.

Which cloud service are you using for your MongoDB deployment? When trying locally, can you access the cloud db (not the local one)? Are you setting env vars correctly (`DB_URL` etc.) on the deployment platform? Do Vercel/Netlify logs say anything useful?

Also, I find Data Proxy + Supabase to be quite unreliable, I had to implement retries to make it work properly but I still get crashes half of the time: https://rakkas-realworld.vercel.app/ I beleive Data Proxy to be the culprit because my Node deployment works fine pretty much all the time: https://realworld.rakkasjs.org/

(Discussions now enabled).

**Comment by sharmapukar217** [comment]
> 

vercel build logs are all clear but on developer console i get
`Uncaught Error: Minified React error #419; visit https://reactjs.org/docs/error-decoder.html?invariant=419 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Sp (index.fd6571f3.js:32:8921)
    at Lc (index.fd6571f3.js:32:7407)
    at Kc (index.fd6571f3.js:32:45891)
    at Vc (index.fd6571f3.js:32:39821)
    at Np (index.fd6571f3.js:32:39752)
    at wl (index.fd6571f3.js:32:39610)
    at Uc (index.fd6571f3.js:32:34714)
    at E (index.fd6571f3.js:17:1562)
    at MessagePort.gn (index.fd6571f3.js:17:1930)
/_data/3b7a80f2e95/0/0/d.js:1          Failed to load resource: the server responded with a status of 500 ()
index.fd6571f3.js:40 Uncaught (in promise) Error: Internal Server Error
    at index.fd6571f3.js:40:31520
index.fd6571f3.js:32 Error: Internal Server Error
    at index.fd6571f3.js:40:31520
bo @ index.fd6571f3.js:32
ln-dashboard.vercel.app/:1          Failed to load resource: the server responded with a status of 500 ()`

**Comment by sharmapukar217** [comment]
I am using mongodb atlas cloud and yes all the database are correctly setup.

**Comment by sharmapukar217** [comment]
despite I'm not even running any queries. I'm just using the enums and i ran into problem

**Comment by cyco130** [comment]
Thanks for the info. I'll have a look into MongoDB specifically. Rakkas Realworld deserves a MongoDB port anyway :)

**Comment by sharmapukar217** [comment]
I guess that was not the problem with rakkasjs. Instead that was error with the vite and was not able to correctly resolve `.prisma/client/index-browser` as it starts with a period. For now I got solution by adding alias like this:
```ts
resolve: {
    alias: {
      ".prisma/client/index-browser": "./node_modules/.prisma/client/index-browser.js"
    }
  },

**Comment by sharmapukar217** [comment]
Ok that was the fix. And now its working and my app is happily running on vercel.

**Comment by cyco130** [comment]
Weird, it maybe a `yarn`/`vite` problem, I never needed that kind of alias with `pnpm`. I'll add a prisma example soon and make sure it works with all package managers.

Glad your problem has been solved though :)

**Comment by sharmapukar217** [comment]
Oh, I forgot to mention, yes that alias to fix ESM/CJS compatibility is also needed, but that was needed when I imported PrismaClient, and the one I mentioned was to use enums ( not the types, the actual enums ). It seems that many other were also having [similar issue](https://github.com/prisma/prisma/issues/12504)

**Comment by cyco130** [comment]
Oh, OK, I think I see why it's happening now. Maybe using `import type` can prevent you from pulling in the browser bundle?

I'm considering adding [consistent type imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md) to my ESLint rules. Rollup (which Vite relies on) and ESBuild still have problems pruning type-only imports.

**Comment by sharmapukar217** [comment]
> Maybe using `import type` can prevent you from pulling in the browser bundle?
Isn't this just importing typedef for the enum? But I was using the actual enum values . eg: I have role enum with a long list of role and to show the available roles on browser, i was importing enum and printing the values to DOM. Maybe there are some problem but atleast for now I can use rakkasjs with prisma and both are shining well ❤️
