### ISSUE TITLE
No HMR on api routes

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#77]
When I change the contents of api routes or `entry-hattip.ts` file, instead of hot reloading, it fully reloads the browser. Is this intentional or something ?

**Comment by cyco130** [comment]
It's the only safe option I can think of. Rakkas doesn't know what API routes are used in which files so it can't tell what to refetch. I can add an option to prevent the full reload on server-side file changes but then nothing will not be refetched.

Maybe we can invalidate all queries but it's not gonna work if you're using something other than `useQuery`. Do you have an idea on how to solve this?

**Comment by sharmapukar217** [comment]
I'll inform you if I got any ideas on this.
