### ISSUE TITLE
Swap useSSM parameter order

### ISSUE THREAD

**Issue by nitedani** [rakkasjs/rakkasjs#80]
Right now my custom mutation hook looks like this:
```ts
export const usePatchVideo = () => {
  const queryClient = useQueryClient();
  const methods = useSSM(
    async (
      ctx,
      {
        videoId,
        patchVideoMetadata,
      }: {
        videoId: string;
        patchVideoMetadata: PatchVideoMetadata;
      }
    ) =>
      videoManagementApi.updateVideoMetadataVideosVideoIdPatch({
        videoId,
        patchVideoMetadata,
      }),
    {
      onSuccess() {
        queryClient.invalidateQueries((key) => key.includes("videos"));
      },
    }
  );
  return methods.mutateAsync;
};
```

If the useSSM parameters(ctx, variables) would be swapped(variables,ctx), then the variable types could be inferred from the mutation function and the code could look like this:
```ts
export const usePatchVideo = () => {
  const queryClient = useQueryClient();
  const methods = useSSM(
    videoManagementApi.updateVideoMetadataVideosVideoIdPatch,
    {
      onSuccess() {
        queryClient.invalidateQueries((key) => key.includes("videos"));
      },
    }
  );
  return methods.mutateAsync;
};
```

Other than swapping the parameters, is there a way to let typescript discover the variable types?

**Comment by cyco130** [comment]
Are you sure you're not gonna need anything from the context in  the API function? Like an authentication check or something?
If so, you could change it to accept `(ctx: RequestContext, vars: { videoId: string; patchVideoMetadata: PatchVideoMetadata }`.

The current argument order allows us to use mutations with no vars:

```ts
const x = useSSM((ctx) => { /* Do something */ });

x.mutate(); // No vars required
```

I also think this order is what people coming from `react-query` would expect.

**Comment by nitedani** [comment]
All right :)
