### ISSUE TITLE
Render modes

### ISSUE THREAD

**Issue by cyco130** [rakkasjs/rakkasjs#9]
We should support the following render modes:

## SSR
This is the current default. The page is rendered on demand on the server-side and hydrated on the client.

## Client
A placeholder is sent by the server and the page is rendered on the client.

## Static
The page is rendered at build time and served from the file system to be hydrated on the client.

**EDIT:** We'll consider incremental rendering (#23) in a later version.

**Comment by cyco130** [comment]
Closed in #24

**Comment by peteruithoven** [comment]
This ("Incremental static generation") is mentioned as planned on: https://rakkasjs.org/guide/feature-comparison ?

**Comment by cyco130** [comment]
@peteruithoven The docs are outdated, it should link to #24. Will fix ASAP, thanks for the heads up. We originally plan to support it along with client/server/static pages but prioritized serverless deploys instead so I opened a new issue for it.
