### ISSUE TITLE
Todo example with js doesn't work

### ISSUE THREAD

**Issue by pyrossh** [rakkasjs/rakkasjs#97]
Trying to run the todo example but only with js results in this error,
```
Error: Cannot find module 'src/crud' imported from '~/my-rakkas-app/src/routes/todo/Todo.jsx'
    at nodeImport (~/my-rakkas-app/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52451:25)
    at ssrImport (~e/my-rakkas-app/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52374:20)
    at eval (/src/routes/todo/Todo.jsx:9:37)
    at async instantiateModule (~/my-rakkas-app/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52420:9) {
  code: 'ERR_MODULE_NOT_FOUND'
```

I fixed it by adding this to the vite.config.js,
```
resolve: {
    alias: {
      'src': path.resolve(__dirname, 'src'),
    },
  }
```
And created jsconfig.json for autocomplete,
```
{
  "compilerOptions": {
    "paths": {
      "src/*": ["./src/*"]
    }
  }
}
```
I tried looking at the example code to create a PR but seems like it does some compilation so wanted to clarify first.

**Comment by cyco130** [comment]
Thank you for reporting!

> seems like it does some compilation

Yes, I use [detype](https://github.com/cyco130/detype) to generate JS examples from TS, which saves a lot of work but is prone to errors like this :sweat_smile: 

Fixed in `0.7.0-next.1` (`@next`) and `0.6.19` (`@latest`).
